version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: incidencias_db
      DB_USERNAME: postgres
      DB_PASSWORD: password0809
    depends_on:
      - postgres

  caddy:
    image: caddy:2-alpine
    container_name: caddy_web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: incidencias_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password0809
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  caddy_data:
  caddy_config: